version: 2

sources:
  - name: jaffle_shop
    database: til_portfolio_projects
    schema: dbt_ehughes
    tables:
      - name: raw_jaffle_shop__orders
      - name: raw_jaffle_shop__customers